# Generated by Django 2.2 on 2019-04-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicblog', '0004_auto_20190419_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
