# Generated by Django 2.2 on 2019-04-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicblog', '0005_song_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='id',
        ),
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=models.SlugField(default='musicpost', max_length=250, primary_key=True, serialize=False),
        ),
    ]
