# Generated by Django 2.2 on 2019-04-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicblog', '0006_auto_20190420_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=models.SlugField(max_length=250, primary_key=True, serialize=False, unique=True),
        ),
    ]
