# Generated by Django 2.2 on 2019-04-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicblog', '0008_auto_20190420_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='id',
        ),
        migrations.AddField(
            model_name='song',
            name='slug',
            field=models.SlugField(default=1, max_length=250, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
