# Generated by Django 2.2 on 2019-04-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicblog', '0010_auto_20190420_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
